### ISSUE TITLE
PetOwnerDetailView errors

### ISSUE THREAD

**Issue by mostarrcoding** [mostarrcoding/pet-memorial#2]
```
<html><body>
<!--StartFragment--><div id="summary">
  <h1>OperationalError
       at /owner/AwVFG/</h1>
  <pre class="exception_value">no such table: pet_profile_petphoto_pets</pre>
  

Request Method: | GET
-- | --
http://127.0.0.1:8000/owner/AwVFG/
4.2.5
OperationalError
no such table: pet_profile_petphoto_pets
C:\Users\starr\Code\pet-memorial\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py, line 328, in execute
pet_profile.views.PetOwnerDetailView
C:\Users\starr\Code\pet-memorial\.venv\Scripts\python.exe
3.11.5
['C:\\Users\\starr\\Code\\pet-memorial',  'F:\\computers\\python',  'C:\\Users\\starr\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',  'C:\\Users\\starr\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',  'C:\\Users\\starr\\AppData\\Local\\Programs\\Python\\Python311\\Lib',  'C:\\Users\\starr\\AppData\\Local\\Programs\\Python\\Python311',  'C:\\Users\\starr\\Code\\pet-memorial\\.venv',  'C:\\Users\\starr\\Code\\pet-memorial\\.venv\\Lib\\site-packages']
Mon, 18 Sep 2023 05:31:55 +0000

</div><!--EndFragment-->
</body>
</html>
```

**Comment by mostarrcoding** [comment]
I don't understand why it thinks this table is there, there is no code that defines this table.

**Comment by cristianjs19** [comment]
Hello @mostarrcoding, I have experience with Django apps, maybe I can help you with this. Reach me out at my email, cristianjs19@gmail.com.

**Comment by mostarrcoding** [comment]
> Hello @mostarrcoding, I have experience with Django apps, maybe I can help you with this. Reach me out at my email, [cristianjs19@gmail.com](mailto:cristianjs19@gmail.com).

Thanks for the reply, @cristianjs19. I hesitate to rely on others when I should be self-sufficient (in such basic matters) but I'll give it a thought. Thank you for the offer.

**Comment by cristianjs19** [comment]
@mostarrcoding  Oh sure, don’t worry! To be self-suficient it’s one of the most valuable skills around that matter. But sometimes a bit of help is needed also. In that case let me know anything, and we can take a look!

**Comment by mostarrcoding** [comment]
> @mostarrcoding Oh sure, don’t worry! To be self-suficient it’s one of the most valuable skills around that matter. But sometimes a bit of help is needed also. In that case let me know anything, and we can take a look!

Thank you, @cristianjs19. I really appreciate the offer. Just been kind of psychologically swamped/mugged lately.
